"""Create auto-fix PRs via the GitHub API."""

from __future__ import annotations

import json
import logging
import os
import subprocess

logger = logging.getLogger(__name__)


def _run_git(args: list[str], **kwargs) -> subprocess.CompletedProcess:
    """Run a git command with standard error handling."""
    result = subprocess.run(
        args,
        capture_output=True,
        text=True,
        timeout=60,
        **kwargs,
    )
    if result.returncode != 0:
        logger.warning("Command %s failed: %s", " ".join(args), result.stderr.strip())
    return result


def create_fix_pr(
    fix_description: str,
    fix_diff: str,
    failure_class: str,
    run_id: int | None = None,
) -> str | None:
    """Create a branch with the fix and open a PR.

    Returns the PR URL if successful, None otherwise.
    Requires GITHUB_TOKEN and git to be available.
    """
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")

    if not token or not repo:
        logger.error("GITHUB_TOKEN or GITHUB_REPOSITORY not set — cannot create PR")
        return None

    if not fix_diff or not fix_diff.strip():
        logger.error("Empty fix_diff — nothing to apply")
        return None

    run_id = run_id or int(os.environ.get("GITHUB_RUN_ID", 0))
    base_branch = os.environ.get("GITHUB_REF_NAME", "main")
    fix_branch = f"ci-fix/{failure_class}-{run_id}"

    original_branch = None
    try:
        # Remember current branch/ref to restore later
        result = _run_git(["git", "rev-parse", "--abbrev-ref", "HEAD"])
        if result.returncode == 0:
            original_branch = result.stdout.strip()

        # Configure git identity for the commit
        _run_git(["git", "config", "user.name", "CI Agent Bot"])
        _run_git(["git", "config", "user.email", "ci-agent@scp-platform.noreply"])

        # Create and checkout fix branch
        result = _run_git(["git", "checkout", "-b", fix_branch])
        if result.returncode != 0:
            logger.error("Failed to create branch %s", fix_branch)
            return None

        # Apply the diff
        result = subprocess.run(
            ["git", "apply", "--allow-empty"],
            input=fix_diff,
            text=True,
            capture_output=True,
            timeout=30,
        )

        if result.returncode != 0:
            logger.error("Failed to apply diff: %s", result.stderr.strip())
            return None

        # Check there are actual changes to commit
        status = _run_git(["git", "status", "--porcelain"])
        if not status.stdout.strip():
            logger.warning("No changes after applying diff — nothing to commit")
            return None

        # Commit
        result = _run_git([
            "git", "commit", "-a", "-m",
            f"ci-fix: {fix_description}\n\nAuto-generated by CI Agent for {failure_class}",
        ])
        if result.returncode != 0:
            logger.error("Failed to commit: %s", result.stderr.strip())
            return None

        # Push using GITHUB_TOKEN in the URL
        push_url = f"https://x-access-token:{token}@github.com/{repo}.git"
        result = _run_git(["git", "push", push_url, fix_branch])
        if result.returncode != 0:
            logger.error("Failed to push: %s", result.stderr.strip())
            return None

        # Create PR via gh CLI
        result = subprocess.run(
            [
                "gh",
                "pr",
                "create",
                "--title",
                f"ci-fix: {fix_description}",
                "--body",
                _pr_body(failure_class, run_id, fix_description),
                "--base",
                base_branch,
                "--head",
                fix_branch,
                "--label",
                "ci-auto-fix,bot",
            ],
            capture_output=True,
            text=True,
            timeout=30,
            env={**os.environ, "GH_TOKEN": token},
        )

        if result.returncode == 0:
            pr_url = result.stdout.strip()
            logger.info("Created PR: %s", pr_url)
            return pr_url

        logger.error("Failed to create PR: %s", result.stderr.strip())
        return None

    except subprocess.TimeoutExpired:
        logger.error("Command timed out during PR creation")
        return None
    except Exception as exc:
        logger.error("Unexpected error creating fix PR: %s", exc)
        return None
    finally:
        # Return to original branch
        restore = original_branch or base_branch
        _run_git(["git", "checkout", restore])


def _pr_body(failure_class: str, run_id: int, description: str) -> str:
    return f"""## CI Agent Auto-Fix

**Failure class:** `{failure_class}`
**Triggered by:** Run #{run_id}

### What changed
{description}

### Why
The CI agent detected a recurring build failure and generated this fix automatically.

---
_This PR was created automatically by the CI Agent. Please review before merging._
"""
