"""Create auto-fix PRs via the GitHub API."""

from __future__ import annotations

import json
import os
import subprocess


def create_fix_pr(
    fix_description: str,
    fix_diff: str,
    failure_class: str,
    run_id: int | None = None,
) -> str | None:
    """Create a branch with the fix and open a PR.

    Returns the PR URL if successful, None otherwise.
    Requires GITHUB_TOKEN and git to be available.
    """
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")

    if not token or not repo:
        return None

    run_id = run_id or int(os.environ.get("GITHUB_RUN_ID", 0))
    base_branch = os.environ.get("GITHUB_REF_NAME", "main")
    fix_branch = f"ci-fix/{failure_class}-{run_id}"

    try:
        # Create and checkout fix branch
        subprocess.run(["git", "checkout", "-b", fix_branch], check=True, capture_output=True)

        # Apply the diff
        result = subprocess.run(
            ["git", "apply", "--allow-empty"],
            input=fix_diff,
            text=True,
            capture_output=True,
        )

        if result.returncode != 0:
            return None

        # Commit
        subprocess.run(["git", "add", "-A"], check=True, capture_output=True)
        subprocess.run(
            ["git", "commit", "-m", f"ci-fix: {fix_description}\n\nAuto-generated by CI Agent for {failure_class}"],
            check=True,
            capture_output=True,
        )

        # Push
        subprocess.run(
            ["git", "push", "origin", fix_branch],
            check=True,
            capture_output=True,
            env={**os.environ, "GIT_TOKEN": token},
        )

        # Create PR via gh CLI
        result = subprocess.run(
            [
                "gh",
                "pr",
                "create",
                "--title",
                f"ci-fix: {fix_description}",
                "--body",
                _pr_body(failure_class, run_id, fix_description),
                "--base",
                base_branch,
                "--label",
                "ci-auto-fix,bot",
            ],
            capture_output=True,
            text=True,
        )

        if result.returncode == 0:
            return result.stdout.strip()

        return None

    except Exception:
        return None
    finally:
        # Return to original branch
        subprocess.run(["git", "checkout", base_branch], capture_output=True)


def _pr_body(failure_class: str, run_id: int, description: str) -> str:
    return f"""## CI Agent Auto-Fix

**Failure class:** `{failure_class}`
**Triggered by:** Run #{run_id}

### What changed
{description}

### Why
The CI agent detected a recurring build failure and generated this fix automatically.

---
_This PR was created automatically by the CI Agent. Please review before merging._
"""
