"""Auto-generate project documentation from build results and commit history.

Runs after every build and updates the /docs folder with:
  - BUILD_REPORT.md — latest build status, test coverage, security, version
  - CHANGELOG.md — auto-generated from conventional commits
  - ARCHITECTURE.md — auto-detected project structure and modules

All docs are committed back to the repo so they stay in sync with the code.
"""

from __future__ import annotations

import json
import re
import subprocess
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path


@dataclass
class BuildContext:
    """Context collected from the build for doc generation."""
    repo_name: str = ""
    branch: str = ""
    commit_sha: str = ""
    commit_message: str = ""
    version: str = ""
    repo_role: str = ""
    project_type: str = ""
    frameworks: list[str] = field(default_factory=list)
    test_tool: str = ""
    test_count: int = 0
    test_passed: int = 0
    coverage: float = 0.0
    build_status: str = ""
    security_warnings: list[str] = field(default_factory=list)
    build_artifacts: list[str] = field(default_factory=list)
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"))


def _git(args: list[str], cwd: Path) -> str:
    """Run a git command and return stdout."""
    try:
        result = subprocess.run(
            ["git"] + args, capture_output=True, text=True, cwd=cwd, timeout=15,
        )
        return result.stdout.strip() if result.returncode == 0 else ""
    except Exception:
        return ""


def collect_build_context(repo_path: Path, build_plan: dict | None = None) -> BuildContext:
    """Collect build context from the repo and optional build plan."""
    ctx = BuildContext()
    ctx.repo_name = repo_path.name
    ctx.branch = _git(["rev-parse", "--abbrev-ref", "HEAD"], repo_path)
    ctx.commit_sha = _git(["rev-parse", "--short", "HEAD"], repo_path)
    ctx.commit_message = _git(["log", "-1", "--pretty=format:%s"], repo_path)

    # From pyproject.toml
    pyproject = repo_path / "pyproject.toml"
    if pyproject.exists():
        text = pyproject.read_text()
        m = re.search(r'version\s*=\s*"([^"]+)"', text)
        if m:
            ctx.version = m.group(1)
        m = re.search(r'name\s*=\s*"([^"]+)"', text)
        if m:
            ctx.repo_name = m.group(1)

    if build_plan:
        ctx.repo_role = build_plan.get("repo_role", "")
        ctx.project_type = build_plan.get("project_type", "")
        ctx.frameworks = build_plan.get("frameworks", [])
        ctx.test_tool = build_plan.get("test_tool", "")
        ctx.security_warnings = build_plan.get("security_warnings", [])

    return ctx


def generate_build_report(ctx: BuildContext) -> str:
    """Generate BUILD_REPORT.md content."""
    status_icon = "✅" if ctx.build_status == "passed" else "❌" if ctx.build_status == "failed" else "⚠️"

    lines = [
        f"# Build Report — {ctx.repo_name}",
        "",
        f"**Last updated:** {ctx.timestamp}",
        f"**Branch:** `{ctx.branch}` | **Commit:** `{ctx.commit_sha}`",
        f"**Version:** `{ctx.version}`",
        "",
        f"## Status: {status_icon} {ctx.build_status.upper()}",
        "",
        "| Property | Value |",
        "|----------|-------|",
        f"| Role | {ctx.repo_role} |",
        f"| Language | {ctx.project_type} |",
        f"| Frameworks | {', '.join(ctx.frameworks) if ctx.frameworks else 'none'} |",
        f"| Test tool | {ctx.test_tool} |",
        f"| Tests | {ctx.test_passed}/{ctx.test_count} passed |",
        f"| Coverage | {ctx.coverage:.0f}% |",
        "",
    ]

    if ctx.build_artifacts:
        lines.append("## Artifacts")
        lines.append("")
        for a in ctx.build_artifacts:
            lines.append(f"- `{a}`")
        lines.append("")

    if ctx.security_warnings:
        lines.append("## Security Warnings")
        lines.append("")
        for w in ctx.security_warnings:
            lines.append(f"- {w}")
        lines.append("")

    lines.extend([
        "---",
        f"_Auto-generated by SCP CI Agent from commit `{ctx.commit_sha}`_",
    ])

    return "\n".join(lines)


def generate_changelog(repo_path: Path, max_entries: int = 50) -> str:
    """Generate CHANGELOG.md from git log using conventional commits."""
    lines = [
        "# Changelog",
        "",
        "All notable changes to this project are documented automatically from commit history.",
        "",
    ]

    # Get tags in reverse chronological order
    tags_raw = _git(["tag", "--sort=-version:refname"], repo_path)
    tags = [t.strip() for t in tags_raw.splitlines() if t.strip()] if tags_raw else []

    if tags:
        # Generate changelog per tag
        for i, tag in enumerate(tags[:10]):  # Last 10 versions
            prev_tag = tags[i + 1] if i + 1 < len(tags) else ""
            log_range = f"{prev_tag}..{tag}" if prev_tag else tag

            tag_date = _git(["log", "-1", "--format=%ai", tag], repo_path)[:10]
            commits_raw = _git(["log", log_range, "--pretty=format:%s"], repo_path)
            commits = commits_raw.splitlines() if commits_raw else []

            lines.append(f"## {tag} ({tag_date})")
            lines.append("")

            breaking = [c for c in commits if "!" in c.split(":")[0] if ":" in c]
            feats = [c for c in commits if c.lower().startswith("feat") and c not in breaking]
            fixes = [c for c in commits if c.lower().startswith("fix")]
            others = [c for c in commits if c not in breaking and c not in feats and c not in fixes]

            if breaking:
                lines.append("### Breaking Changes")
                for c in breaking:
                    lines.append(f"- {c}")
                lines.append("")
            if feats:
                lines.append("### Features")
                for c in feats:
                    lines.append(f"- {c}")
                lines.append("")
            if fixes:
                lines.append("### Fixes")
                for c in fixes:
                    lines.append(f"- {c}")
                lines.append("")
            if others:
                lines.append("### Other")
                for c in others:
                    lines.append(f"- {c}")
                lines.append("")

        # Unreleased commits (after latest tag)
        unreleased_raw = _git(["log", f"{tags[0]}..HEAD", "--pretty=format:%s"], repo_path)
        if unreleased_raw:
            unreleased = unreleased_raw.splitlines()
            lines.insert(4, "## Unreleased\n")
            for c in unreleased:
                lines.insert(5, f"- {c}")
            lines.insert(5 + len(unreleased), "")
    else:
        # No tags — just list all commits
        all_commits = _git(["log", f"--max-count={max_entries}", "--pretty=format:%h %s (%an, %ar)"], repo_path)
        if all_commits:
            lines.append("## Unreleased")
            lines.append("")
            for line in all_commits.splitlines():
                lines.append(f"- {line}")

    lines.extend(["", "---", "_Auto-generated by SCP CI Agent_"])
    return "\n".join(lines)


def generate_architecture(repo_path: Path) -> str:
    """Generate ARCHITECTURE.md from project structure."""
    lines = [
        f"# Architecture — {repo_path.name}",
        "",
        "Auto-generated project structure and module documentation.",
        "",
        "## Project Structure",
        "",
        "```",
    ]

    # Walk the source tree
    src_dir = repo_path / "src"
    if not src_dir.exists():
        src_dir = repo_path

    for path in sorted(src_dir.rglob("*.py")):
        if any(skip in path.parts for skip in ["__pycache__", ".venv", "venv", "dist", "build", ".egg-info"]):
            continue
        rel = path.relative_to(repo_path)
        depth = len(rel.parts) - 1
        prefix = "│   " * depth + "├── " if depth > 0 else ""
        lines.append(f"{prefix}{rel.name}")

    lines.append("```")
    lines.append("")

    # Document each module
    lines.append("## Modules")
    lines.append("")

    for path in sorted(src_dir.rglob("*.py")):
        if any(skip in path.parts for skip in ["__pycache__", ".venv", "venv", "dist", "build", ".egg-info"]):
            continue
        if path.name == "__init__.py":
            continue

        rel = str(path.relative_to(repo_path))
        try:
            content = path.read_text(errors="ignore")
            # Extract module docstring
            docstring = ""
            m = re.match(r'^"""(.*?)"""', content, re.DOTALL)
            if m:
                docstring = m.group(1).strip().split("\n")[0]

            # Count classes and functions
            classes = re.findall(r"^class (\w+)", content, re.MULTILINE)
            functions = re.findall(r"^def (\w+)", content, re.MULTILINE)
            public_functions = [f for f in functions if not f.startswith("_")]

            lines.append(f"### `{rel}`")
            if docstring:
                lines.append(f"_{docstring}_")
            lines.append("")
            if classes:
                lines.append(f"**Classes:** {', '.join(f'`{c}`' for c in classes)}")
            if public_functions:
                lines.append(f"**Functions:** {', '.join(f'`{f}`' for f in public_functions)}")
            if classes or public_functions:
                lines.append("")

        except Exception:
            pass

    lines.extend(["---", "_Auto-generated by SCP CI Agent_"])
    return "\n".join(lines)


def generate_all_docs(
    repo_path: str,
    build_plan: dict | None = None,
    build_status: str = "passed",
    test_count: int = 0,
    test_passed: int = 0,
    coverage: float = 0.0,
) -> dict[str, str]:
    """Generate all documentation files.

    Returns dict of {filename: content} for files to write to docs/.
    """
    path = Path(repo_path)
    ctx = collect_build_context(path, build_plan)
    ctx.build_status = build_status
    ctx.test_count = test_count
    ctx.test_passed = test_passed
    ctx.coverage = coverage

    # Check for build artifacts
    dist = path / "dist"
    if dist.exists():
        ctx.build_artifacts = [f.name for f in dist.iterdir() if f.is_file()]

    docs = {
        "BUILD_REPORT.md": generate_build_report(ctx),
        "CHANGELOG.md": generate_changelog(path),
        "ARCHITECTURE.md": generate_architecture(path),
    }

    return docs


def write_docs(repo_path: str, docs: dict[str, str]) -> list[str]:
    """Write generated docs to the repo's docs/ folder.

    Returns list of files written.
    """
    path = Path(repo_path) / "docs"
    path.mkdir(exist_ok=True)
    written = []

    for filename, content in docs.items():
        filepath = path / filename
        filepath.write_text(content)
        written.append(f"docs/{filename}")

    return written
